- name: Check whether src dir exists before copying
  local_action: "stat path={{ src }}"
  register: fileinfo

# TODO replace secrets
- name: Copy source to destination
  synchronize:
    src: "{{ src }}"
    dest: "{% if dest is defined %}{{ dest }}{% else %}/home/container{% endif %}"
#    owner: "{{ item.name }}"
#    group: "{{ item.name }}"
    mode: "{{ copy_perms }}"
  when: fileinfo.stat.exists
