- name: Copy global configurations to each server
  include: copy-dir.yml
  vars:
    src: "servers/minecraft/"
  when: bungee_server != "true"

- name: Copy server-specific configurations
  include: copy-dir.yml
  vars:
    src: "servers/{{ server_name }}/"

- name: Update local hash
  copy:
    content: "{{ githash.stdout }}"
    dest: "/home/container/mia-githash"

#- name: Ensure file permissions set properly for each server
#  file:
#    path: "/home/{{ item.name }}/server"
##    owner: "{{ item.name }}"
##    group: "{{ item.name }}"
#    mode: "{{ copy_perms }}"
#    recurse: true
#  with_items:
#    - "{{ minecraft_servers }}"
#    - "{{ bungee_servers }}"
